### ISSUE TITLE
html lang="en"

### ISSUE THREAD

**Issue by Stefan-Espant** [sannevanseeventer/the-startup-responsive-interactieve-website#1]
Gebruik voor een Nederlandse site een lang="nl" ipv een lang="en" .

https://github.com/sannevanseeventer/the-startup-responsive-interactieve-website/blob/186f66cea33d11af22ab6fdc8b1a9a9a65b411a7/index.html#L2

**Comment by sannevanseeventer** [comment]
Aangepast, dank!
